# Generated by Django 4.0.3 on 2022-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('GOD', 'God'), ('MOD', 'Janny'), ('PLEB', 'Plebeian'), ('B&', 'Forsaken')], default='PLEB', max_length=5),
        ),
    ]
