# Generated by Django 4.0.3 on 2022-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='laetusbb_def_avatar.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
